### ISSUE TITLE
500 : Internal Server Error when launching rstudio

### ISSUE THREAD

**Issue by marskar** [binder-examples/r_with_python#2]
I forked this repo, made no commits, and entered the forked repo's url
https://github.com/marskar/r_with_python
into mybinder.org.

When I try to launch rstudio using the url I obtained from mybinder.org
https://mybinder.org/v2/gh/marskar/r_with_python/master?urlpath=rstudio
I get an error: `500 : Internal Server Error`.

On the error page, I can switch to the classic notebook or JupyterLab by editing the url.
Launching the classic notebook or JupyterLab works fine. 
https://mybinder.org/v2/gh/marskar/r_with_python/master
https://mybinder.org/v2/gh/marskar/r_with_python/master?urlpath=lab

The launch rstudio link for your repo 
http://mybinder.org/v2/gh/binder-examples/r_with_python/master?urlpath=rstudio
works fine.

I noticed that after rstudio launches the url based on your repo has a token at the end, something like `/rstudio/?token=SZlYyBCaTY2XUIVknZFxHw`, whereas my rstudio url just ends `/rstudio/`.

How can I launch rstudio from my repo?

**Comment by sebkopf** [comment]
I can confirm that I have the same problem with all my RStudio binder repos that have changed in the last week (jupyter lab works great, RStudio launch fails with `500 : Internal Server Error`) - repos without changes (such as this one) continue to run great. I'm not sure where the problem lies - maybe something changed with the repo2docker backend. @betatim could you advise where to look?

**Comment by betatim** [comment]
Do you remember around which day things started failing for newly built repos? This sounds like we made a change to how repositories are built, deployed it and did not notice.

This would explain why repositories that were already built still work but new ones don't.

**Comment by marskar** [comment]
Hi @betatim, The last time it worked for me was around October 16. https://github.com/marskar/rstudio/commit/2ebfc4a98e416cca7e2845f962f8827dfc24f9e4
That doesn't narrow it down much. Maybe you used rstudio binder more recently @sebkopf?

**Comment by betatim** [comment]
Thanks for reporting this, let's see if we can get this fixed during the day today. It looks like a recent change in a package that we depend on to do the proxy'ing.

Next time you notice something like this (especially when it works for already built but not new ones) feel free to instantly ask about it as it is almost always a regression somewhere and it is easier to find them if they only just appeared :)

**Comment by marskar** [comment]
Sorry for not being clear. I found out that this was not working this past Saturday. I was definitely not procrastinating on filing an issue for months, though I can't promise I haven't done that before. 😄

This is probably a good time to say how much I love Binder and that I use it all the time to teach and share. Back in mid-October, I used Binder to demo RStudio git integration and knitting Rmarkdown to various formats. This past Saturday, I wanted to use Binder to show workflows and best practices for R programmers in RStudio. In the meantime, I've been using Binder for Jupyter notebooks and JupyterLab to teach Python. Earlier this semester, I gave an interactive lecture on Linux and command-line tools 100% in JupyterLab's terminal (without any slides).

The versatility of Binder is impressive and thus far it has worked great. Being able to spin up and share a computational environment with everything installed is tremendous. The ability to switch to a different interface (classic Jupyter notebook, JupyterLab, and RStudio) just by changing the ending of a url (`tree`, `lab`, and `rstudio`) is amazing. Binder has raised the bar for talks, demos, tutorials, etc. and I really appreciate all the work that the Binder team did and does to make it possible. Thank you so much for such an awesome tool!

I see now that there are two related issues on the binderhub repos (where I probably should have filed this issue 😅).
https://github.com/jupyterhub/mybinder.org-deploy/issues/865
https://github.com/jupyterhub/binderhub/issues/751

**Comment by betatim** [comment]
Could you try again with a new commit in your repo? I think this could be fixed now :)

I created jupyterhub/mybinder.org-deploy#865 after seeing this one because I wasn't sure where the bug was. In the end it was in a dependency of a dependency we use :)

**Comment by marskar** [comment]
Yes, it works! I'll close the issue now. Thank you!
